GET http://localhost:8000/health

###
POST http://localhost:8000
Content-Type: application/json

{
    "name":"Abul",
    "country":"BD",
    "rank":4
}

###

GET http://localhost:8000

###

GET http://localhost:8000/xSByBSxlF

###

PATCH http://localhost:8000/sDRNI8Kh_
Content-Type: application/json

{
    "name" : "Abul Kalam"
}
